Repository Rexmoon/moon-store, pull requests merged in 2024-12, with the labels that each got.

#4 MS-17: MS Color palette
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/msDarkBlue.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/msHint.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/msLightBlue.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/msLightGray.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/msPrimary.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/msWhite.colorset/Contents.json
Labels: ready to review

#7 MS-12 - Add login View
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/MSTextField.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/PrimaryButton.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Extensions/View+ScreenSize.swift
  moon-store-mac-os/moon-store-mac-os/Views/Login/LoginView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/MainView.swift
  moon-store-mac-os/moon-store-mac-os/moon_store_mac_osApp.swift
Labels: ready to review

#12 MS-30 Create Alert Manager
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/error.imageset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/error.imageset/error.png
  moon-store-mac-os/moon-store-mac-os/Helpers/AlertManager/AlertManager.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/AlertManager/AlertType.swift
Labels: enhancement, ready to review

#11 MS-28: Service layer added
  moon-store-mac-os/moon-store-mac-os/Helpers/Extensions/Data+String.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/MSError+Helper.swift
  moon-store-mac-os/moon-store-mac-os/Services/BaseNetworkService.swift
  moon-store-mac-os/moon-store-mac-os/Services/MSEndpoint.swift
  moon-store-mac-os/moon-store-mac-os/moon_store_mac_os.entitlements
Labels: ready to review

#14 Ms-38 add login flow
  moon-store-mac-os/moon-store-mac-os/LoginManager/LoginManager.swift
  moon-store-mac-os/moon-store-mac-os/Router/AppRouter.swift
  moon-store-mac-os/moon-store-mac-os/Router/AppTransition.swift
  moon-store-mac-os/moon-store-mac-os/Views/Login/LoginView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/Components/Sidebar.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/MainView.swift
  moon-store-mac-os/moon-store-mac-os/moon_store_mac_osApp.swift
Labels: feature

#15 MS-33: Error handler added
  moon-store-mac-os/moon-store-mac-os/Helpers/Extensions/Data+String.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/MSError+Helper.swift
  moon-store-mac-os/moon-store-mac-os/Services/BaseNetworkService.swift
Labels: feature, ready to review

#16 MS-36 MacOS - Create product list view
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/edit.imageset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/edit.imageset/border_color_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/msDarkGray.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/msGray.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/SearchView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/MainView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductMockData.swift
Labels: feature

#17 MS-34: Login feature
  moon-store-mac-os/moon-store-mac-os/Domain/Models/LoginResponseModel.swift
  moon-store-mac-os/moon-store-mac-os/Domain/Models/RoleModel.swift
  moon-store-mac-os/moon-store-mac-os/Domain/Models/UserModel.swift
  moon-store-mac-os/moon-store-mac-os/Domain/Repositories/AuthenticationRepository.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/MSError+Helper.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Persistence/Models/MockSDModel.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Persistence/SwiftDataError.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Persistence/SwiftDataManager.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Persistence/SwiftDataProvider.swift
  moon-store-mac-os/moon-store-mac-os/LoginManager/LoginManager.swift
  moon-store-mac-os/moon-store-mac-os/Router/AppRouter.swift
  moon-store-mac-os/moon-store-mac-os/Services/BaseNetworkService.swift
  moon-store-mac-os/moon-store-mac-os/Views/Login/LoginView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Login/LoginViewModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/MainView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/MainViewViewModel.swift
  moon-store-mac-os/moon-store-mac-os/moon_store_mac_osApp.swift
Labels: feature, ready to review

#21 MS-53: Change by static method
  moon-store-mac-os/moon-store-mac-os/Helpers/AlertManager/AlertManager.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/AuthenticationManager/AuthenticationManager.swift
  moon-store-mac-os/moon-store-mac-os/Views/Login/LoginViewModel.swift
Labels: enhancement

#24 Add user to main view and remove saveChanges functions
  moon-store-mac-os/moon-store-mac-os/Domain/Models/LoginResponseModel.swift
  moon-store-mac-os/moon-store-mac-os/Domain/Repositories/AuthenticationRepository.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/AuthenticationManager/AuthenticationManager.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/MSError+Helper.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Persistence/SwiftDataManager.swift
  moon-store-mac-os/moon-store-mac-os/Router/AppRouter.swift
  moon-store-mac-os/moon-store-mac-os/Router/AppTransition.swift
  moon-store-mac-os/moon-store-mac-os/Views/Login/LoginView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Login/LoginViewModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/Components/Sidebar.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/MainView.swift
Labels: enhancement

#23 MS-55: MSSPinner feature
  moon-store-mac-os/moon-store-mac-os/Helpers/MSSpinner/MSSpinner.swift
  moon-store-mac-os/moon-store-mac-os/Views/Login/LoginView.swift
Labels: feature

#20 MS-47: Connect products view to backend data
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/msGreen.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/msOrange.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/msYellow.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Domain/Repositories/AuthenticationRepository.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/AlertManager/AlertManager.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/AuthenticationManager/AuthenticationManager.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/MSEmptyListView.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Extensions/View+Extension.swift
  moon-store-mac-os/moon-store-mac-os/Networking/MSEndpoint.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/LoginResponseModel.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/ProductModel.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/ProductResponse.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/RoleModel.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/UserModel.swift
  moon-store-mac-os/moon-store-mac-os/Networking/NetworkManager.swift
  moon-store-mac-os/moon-store-mac-os/Router/AppRouter.swift
  moon-store-mac-os/moon-store-mac-os/Views/Login/LoginView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Login/LoginViewModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/Components/Sidebar.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListViewModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductMockData.swift
Labels: feature, ready to review
