Repository Rexmoon/moon-store, pull requests merged in 2025-01, with the labels that each got.

#27 MS-57
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/MSAsyncImage.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/MSSpinner/MSSpinner.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Persistence/ImageCache.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Persistence/MemoryCache.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListView.swift
Labels: feature, ready to review

#28 fix: remove testing image
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListView.swift
Labels: bug

#29 MS-58: Add product feature
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/MSImagePicker/MSImagePickerUtility.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/MSImagePicker/MSImagePickerView.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Extensions/Binding+Extension.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Extensions/Collection+Empty.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/MSError+Helper.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Managers/ProductManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/CreateProductResponse.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/ProductModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/AddProductView+Edit.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/AddProductViewModel+Edit.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListView.swift
Labels: feature, ready to review

#32 MS-59: Delete product
  moon-store-mac-os/moon-store-mac-os/Helpers/AlertManager/AlertManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Managers/ProductManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/DeleteProductResponse.swift
  moon-store-mac-os/moon-store-mac-os/Networking/NetworkManager.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListViewModel.swift
Labels: feature, ready to review

#34 MS-65: Supply product feature
  moon-store-mac-os/moon-store-mac-os/Networking/Managers/ProductManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/NetworkManager.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListViewModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/SupplyProductView.swift
Labels: feature, ready to merge

#35 MS-64: Product count row
  moon-store-mac-os/moon-store-mac-os/Networking/Managers/ProductManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/ProductCountModel.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/ProductCountResponse.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListViewModel.swift
Labels: feature, ready to review

#38 MS-67: Export product list
  moon-store-mac-os/moon-store-mac-os/Helpers/Exporter/ExporterButton.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Exporter/FileFactory.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListViewModel.swift
Labels: feature, ready to review

#36 MS-61: Product detail modal view
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductDetailView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListView.swift
Labels: feature, ready to review, ready to merge

#39 Fixing product UI issues
  moon-store-mac-os/moon-store-mac-os/Helpers/Modifiers/SpinnerModifier.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ListView/ProductListConstants.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ListView/ProductListView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ListView/ProductTableTitle.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListView.swift
Labels: bug, enhancement

#41 MS-70: Update password
  moon-store-mac-os/moon-store-mac-os/Helpers/MSError+Helper.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Managers/UserManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/NetworkManager.swift
  moon-store-mac-os/moon-store-mac-os/Views/Profile/ProfileView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Profile/ProfileViewModel.swift
Labels: feature, ready to review

#30 MS-48: Connect Users view to backend data
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/HeaderView.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Extensions/Date+String.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/UserResponse.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/UserConstants.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/UserListViewModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/UserMock.swift
Labels: changes needed

#42 MS-69: Backup feature
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/msEmptyImage.imageset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/msEmptyImage.imageset/msEmptyImage.png
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/MSEmptyListView.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Managers/BackupManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/BackupListResponseModel.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/BackupResponseModel.swift
  moon-store-mac-os/moon-store-mac-os/Networking/NetworkManager.swift
  moon-store-mac-os/moon-store-mac-os/Views/Backup/BackupView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Backup/BackupViewModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/MainView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/Screen.swift
Labels: feature, ready to review

#43 MS-83: Invite user by email
  moon-store-mac-os/moon-store-mac-os/Helpers/Extensions/String+Email.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/InviteUser/InviteUserView.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/InviteUser/InviteUserViewModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/UserInviteView.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
Labels: feature, ready to review

#45 MS-79: Edit user
  moon-store-mac-os/moon-store-mac-os/Networking/Managers/UserManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/RoleModel.swift
  moon-store-mac-os/moon-store-mac-os/Networking/NetworkManager.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/Screen.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/UserConstants.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/UserListViewModel.swift
Labels: feature, ready to review

#46 MS-72: Register user feature
  moon-store-mac-os/moon-store-mac-os/Helpers/Extensions/Date+String.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Managers/AuthenticationManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Managers/UserManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/UserRegisterModel.swift
  moon-store-mac-os/moon-store-mac-os/Networking/NetworkManager.swift
  moon-store-mac-os/moon-store-mac-os/Views/Login/LoginView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Login/LoginViewModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/RegisterUser/RegisterUserView.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/RegisterUser/RegisterUserViewModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/UserConstants.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/UserListViewModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/User/UserTableHeader.swift
Labels: feature, ready to review

#47 MS-82/85/88: Get invoices / Preview invoices / Export invoices
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/MSDivider.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Exporter/ExporterButton.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Exporter/FileFactory.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Extensions/Double+Extension.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Managers/InvoiceManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/InvoiceDetailModel.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/InvoiceModel.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/InvoiceModelResponse.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/InvoiceSaleModel.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/InvoiceSaleRowModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/Invoice/InvoiceList/InvoiceListView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Invoice/InvoiceList/InvoiceListViewModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/Invoice/InvoicePreview/InvoicePreviewView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/MainView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/Screen.swift
Labels: feature, ready to review

#48 Update README.md
  README.md
Labels: enhancement

#50 Fixing Add Product issues
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/MSImagePicker/MSImagePickerView.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/MSTextField.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Extensions/Binding+Extension.swift
  moon-store-mac-os/moon-store-mac-os/Views/Product/AddProductView+Edit.swift
Labels: bug

#51 MS-87: Invoices count
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/TextCounterView.swift
  moon-store-mac-os/moon-store-mac-os/Networking/MSEndpoint.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Managers/InvoiceManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/InvoiveCountModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/Invoice/InvoiceList/InvoiceListView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Invoice/InvoiceList/InvoiceListViewModel.swift
Labels: feature, ready to review

#52 MS-86: Create invoice feature
  moon-store-mac-os/.DS_Store
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/PrimaryButton.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Managers/InvoiceManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/InvoiceSaleModel.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/InvoiceSaleRowModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/Invoice/CreateInvoice/CreateInvoiceView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Invoice/CreateInvoice/CreateInvoiceViewModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/Invoice/InvoiceList/InvoiceListViewModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/Invoice/InvoicePreview/InvoicePreviewView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/MainView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/Screen.swift
Labels: feature, ready to review

#53 MS-89: Connect charts with backend data
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/Charts/AreaChart.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/Charts/BarChart.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/Charts/ChartData.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/InformationCard/CardGraphicModel.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/InformationCard/Information.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/InformationCard/InformationCard.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Extensions/Date+String.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Managers/UserManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/UserChartResponse.swift
  moon-store-mac-os/moon-store-mac-os/Views/Graphics/GraphicsView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Graphics/GraphicsViewModel.swift
Labels: feature, ready to review

#54 MS-94: Logo and icon
  moon-store-mac-os/moon-store-mac-os.xcodeproj/project.pbxproj
  moon-store-mac-os/moon-store-mac-os.xcodeproj/xcshareddata/xcschemes/moon-store-mac-os.xcscheme
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/AppIcon.appiconset/1024-mac.png
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/AppIcon.appiconset/128-mac.png
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/AppIcon.appiconset/16-mac.png
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/AppIcon.appiconset/256-mac.png
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/AppIcon.appiconset/32-mac.png
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/AppIcon.appiconset/512-mac.png
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/AppIcon.appiconset/64-mac.png
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/AppIcon.appiconset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Colors/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Colors/msBlack.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Colors/msDarkBlue.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Colors/msDarkGray.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Colors/msGray.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Colors/msGreen.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Colors/msHint.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Colors/msLightBlue.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Colors/msLightGray.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Colors/msOrange.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Colors/msPrimary.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Colors/msWhite.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Colors/msYellow.colorset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Images/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Images/edit.imageset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Images/edit.imageset/border_color_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Images/error.imageset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Images/error.imageset/error.png
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Images/msEmptyImage.imageset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Images/msEmptyImage.imageset/msEmptyImage.png
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Images/msLogo.imageset/Contents.json
  moon-store-mac-os/moon-store-mac-os/Assets.xcassets/Images/msLogo.imageset/MS Store Logo.png
  moon-store-mac-os/moon-store-mac-os/Helpers/Components/MSLogo.swift
  moon-store-mac-os/moon-store-mac-os/Views/Invoice/InvoicePreview/InvoicePreviewView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Main/Components/Sidebar.swift
Labels: feature

#56 MS-90-MS-91: Export graphics and invoice preview as PDF
  moon-store-mac-os/moon-store-mac-os/Helpers/Exporter/PDFExporterButton.swift
  moon-store-mac-os/moon-store-mac-os/Helpers/Extensions/String+Date.swift
  moon-store-mac-os/moon-store-mac-os/Views/Graphics/GraphicsView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Invoice/CreateInvoice/CreateInvoiceView.swift
  moon-store-mac-os/moon-store-mac-os/Views/Invoice/InvoicePreview/InvoicePreviewView.swift
Labels: feature

#57 MS-95: Restore database
  moon-store-mac-os/moon-store-mac-os/Networking/Managers/BackupManager.swift
  moon-store-mac-os/moon-store-mac-os/Networking/Models/BackupResponseModel.swift
  moon-store-mac-os/moon-store-mac-os/Views/Backup/BackupView.swift
Labels: feature
